# Generated by Django 5.2.6 on 2025-10-06 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vistoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='relatorios/logos/')),
                ('texto_apresentacao', models.TextField(blank=True, default='')),
                ('texto_metodologia', models.TextField(blank=True, default='')),
                ('texto_conclusao', models.TextField(blank=True, default='')),
                ('assinantes', models.JSONField(blank=True, default=list)),
                ('incluir_mapa_nc', models.BooleanField(default=True)),
                ('incluir_sem_registro', models.BooleanField(default=False)),
                ('ocultar_contas_zeradas', models.BooleanField(default=True)),
                ('ordenar_anexos', models.CharField(choices=[('valor', 'Por valor'), ('conta', 'Por conta')], default='conta', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('inventario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_relatorio', to='vistoria.inventario')),
            ],
        ),
    ]
