services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - einv-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    environment:
      # --- Django / proxy / paths ---
      - SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
      - CSRF_TRUSTED_ORIGINS
      - TIME_ZONE
      - USE_X_FORWARDED_HOST=1
      - STATIC_ROOT=/app/staticfiles
      - MEDIA_ROOT=/app/media

      # --- Credenciais do banco (propagadas ao web) ---
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

      # --- Formatos aceitos pelo settings.py ---
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DATABASE_URL

      # --- Fallback direto para o driver (manage.py) ---
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE
      - PGUSER
      - PGPASSWORD

      # --- Sem TLS interno ---
      - SESSION_COOKIE_SECURE=0
      - CSRF_COOKIE_SECURE=0
      - SECURE_SSL_REDIRECT=0

    command: >-
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             exec gunicorn einventarioifce.wsgi:application -b 0.0.0.0:8000 -w 3 --timeout 600"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - einv-net

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
    networks:
      - einv-net
      - dokploy-network

    labels:
      traefik.enable: "true"

      # --- Regra super simples: combina QUALQUER caminho
      traefik.http.routers.einv.rule: PathPrefix(`/`)
      # Use ambos entrypoints, caso o Dokploy tenha nomes/padrões diferentes
      traefik.http.routers.einv.entrypoints: web,websecure
      # Não exigir TLS (como rodamos só HTTP interno)
      traefik.http.routers.einv.tls: "false"
      traefik.http.routers.einv.priority: "1"

      # --- Aponta p/ este serviço Nginx e porta interna 80
      traefik.http.routers.einv.service: einv
      traefik.http.services.einv.loadbalancer.server.port: "80"

      # --- Rede do Traefik (ajuste se no seu host o nome for outro)
      traefik.docker.network: dokploy-network

volumes:
  pg_data:
  static_volume:
  media_volume:

networks:
  einv-net:
    driver: bridge
  dokploy-network:
    external: true
