# Generated by Django 5.2.6 on 2025-09-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tombamento', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='NUMERO')),
                ('status', models.CharField(blank=True, max_length=32, null=True, verbose_name='STATUS')),
                ('ed', models.CharField(blank=True, max_length=64, null=True, verbose_name='ED')),
                ('conta_contabil', models.CharField(blank=True, max_length=64, null=True, verbose_name='CONTA CONTABIL')),
                ('descricao', models.TextField(verbose_name='DESCRICAO')),
                ('rotulos', models.TextField(blank=True, null=True, verbose_name='RÓTULOS')),
                ('carga_atual', models.CharField(blank=True, max_length=255, null=True, verbose_name='CARGA ATUAL')),
                ('setor_responsavel', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='SETOR DO RESPONSÁVEL')),
                ('campus_carga', models.CharField(blank=True, max_length=255, null=True, verbose_name='CAMPUS DA CARGA')),
                ('carga_contabil', models.CharField(blank=True, max_length=255, null=True, verbose_name='CARGA CONTÁBIL')),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='VALOR AQUISIÇÃO')),
                ('valor_depreciado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='VALOR DEPRECIADO')),
                ('numero_nota_fiscal', models.CharField(blank=True, max_length=64, null=True, verbose_name='NUMERO NOTA FISCAL')),
                ('numero_serie', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='NÚMERO DE SÉRIE')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='DATA DA ENTRADA')),
                ('data_carga', models.DateField(blank=True, null=True, verbose_name='DATA DA CARGA')),
                ('fornecedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='FORNECEDOR')),
                ('sala', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='SALA')),
                ('estado_conservacao', models.CharField(blank=True, max_length=32, null=True, verbose_name='ESTADO DE CONSERVAÇÃO')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Bem',
                'verbose_name_plural': 'Bens',
                'ordering': ['tombamento'],
            },
        ),
    ]
