# Generated by Django 5.2.6 on 2025-09-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_setor_sala'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together={('nome', 'setor', 'bloco')},
        ),
    ]
