# Generated by Django 5.2.6 on 2025-09-24 21:10

from django.db import migrations

from django.db.models import Count, Min

def dedup_sala_nome_bloco(apps, schema_editor):
    Sala = apps.get_model('patrimonio', 'Sala')

    # Agrupa por (nome, bloco) e mantém o menor id (mais antigo)
    dupes = (Sala.objects
             .values('nome', 'bloco')
             .annotate(cnt=Count('id'), keep_id=Min('id'))
             .filter(cnt__gt=1))

    # Remove todos os demais ids do mesmo par (nome, bloco)
    for g in dupes:
        nome = g['nome']
        bloco = g['bloco']
        keep_id = g['keep_id']
        (Sala.objects
             .filter(nome=nome, bloco=bloco)
             .exclude(id=keep_id)
             .delete())


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0003_alter_sala_unique_together'),
    ]

    operations = [

        migrations.RunPython(dedup_sala_nome_bloco, reverse_code=migrations.RunPython.noop),

        migrations.AlterUniqueTogether(
            name='sala',
            unique_together={('nome', 'bloco')},
        ),
        migrations.RemoveField(
            model_name='sala',
            name='setor',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
