# Generated by Django 5.2.6 on 2025-09-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_alter_sala_unique_together_remove_sala_setor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ['-bens_count', 'nome'], 'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AddField(
            model_name='sala',
            name='bens_count',
            field=models.IntegerField(default=0, verbose_name='Bens'),
        ),
    ]
