# Generated by Django 5.2.6 on 2025-10-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0005_alter_sala_options_sala_bens_count'),
        ('vistoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-ano']},
        ),
        migrations.AlterModelOptions(
            name='vistoriabem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vistoriaextra',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='inventario',
            name='unico_inventario_ativo',
        ),
        migrations.RemoveIndex(
            model_name='vistoriabem',
            name='vistoria_vi_inventa_2caa97_idx',
        ),
        migrations.RemoveIndex(
            model_name='vistoriabem',
            name='vistoria_vi_inventa_53dcb0_idx',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='data_inicio',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='incluir_livros',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='atualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vistorias_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='avaria_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='bem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.bem'),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='confere_descricao',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='confere_estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='confere_local',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='confere_numero_serie',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='confere_responsavel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vistorias_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='descricao_obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='divergente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='estado_obs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='etiqueta_condicao',
            field=models.CharField(blank=True, choices=[('BOA', 'Boa'), ('DANIFICADA', 'Danificada'), ('ILEGIVEL', 'Ilegível')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='etiqueta_possui',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='foto_marcadagua',
            field=models.ImageField(blank=True, null=True, upload_to='vistorias/'),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistoria.inventario'),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='numero_serie_obs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='responsavel_obs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='sala_obs_bloco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='sala_obs_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriabem',
            name='status',
            field=models.CharField(choices=[('ENCONTRADO', 'Encontrado'), ('NAO_ENCONTRADO', 'Não encontrado')], default='ENCONTRADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='vistoriaextra',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vistoriaextra',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extras_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vistoriaextra',
            name='descricao_obs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vistoriaextra',
            name='estado_obs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriaextra',
            name='etiqueta_condicao',
            field=models.CharField(blank=True, choices=[('BOA', 'Boa'), ('DANIFICADA', 'Danificada'), ('ILEGIVEL', 'Ilegível')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriaextra',
            name='etiqueta_possui',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vistoriaextra',
            name='foto_marcadagua',
            field=models.ImageField(blank=True, null=True, upload_to='vistorias/'),
        ),
        migrations.AlterField(
            model_name='vistoriaextra',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistoria.inventario'),
        ),
        migrations.AlterField(
            model_name='vistoriaextra',
            name='numero_serie_obs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriaextra',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriaextra',
            name='responsavel_obs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriaextra',
            name='sala_obs_bloco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vistoriaextra',
            name='sala_obs_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
